import Head from "next/head";
import Image from "next/image";

import Navbar from "../components/Navbar/Navbar";
import Hero from "./Hero";
import About from "./About";
import Skills from "./skills";
import Works from "./Works";
import Contact from "./Contact";
import Sidebar from "../components/Sidebar/Sidebar";


export default function Home() {
  return (
    <div className="m-0 scrollbar-hide">
      <Head>
        <title>Heshan Rathnayake | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Capriola&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Major+Mono+Display&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Navbar />
      <Sidebar />
      <Hero/>
    </div>
  );
}
