import Head from 'next/head'
import Image from 'next/image'
import Hero from './Hero'
import Navbar from '../components/Navbar/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Heshan Rathnayake | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link
        href="https://fonts.googleapis.com/css2?family=Capriola&display=swap"
        rel="stylesheet"
      />
      <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800&display=swap" rel="stylesheet" /> 
      <link href="https://fonts.googleapis.com/css2?family=Major+Mono+Display&display=swap" rel="stylesheet" /> 
      </Head>
      
      <Navbar />
      <div className='snap-y snap-mandatory h-[100vh] w-screen overflow-y-scroll'>
        <Hero />
        <div id='about' className='snap-start bg-black-200 w-screen h-full flex items-center justify-center text-8xl'>1</div>
        <div id='skills' className='snap-start bg-black-200 w-screen h-full flex items-center justify-center text-8xl'>2</div>
        <div id='works' className='snap-start bg-black-200 w-screen h-full flex items-center justify-center text-8xl'>3</div>
        <div id='contact' className='snap-start bg-black-200 w-screen h-full flex items-center justify-center text-8xl'>4</div>
      </div>
    </div>
  )
}
